language: node_js
node_js: '10'

env:
  global:
    - secure: E8kF0dxW6F5d6QbxZ/oO+YiUN2U3dTStfNWCVKBqMCAoe6jnumbOa8+LMJ8ISiI1K1bR4PDH8rUzs2nrZaPO66DdhjR0pur4Qds4ecuwz2FVzAjvbtye3dA5llsoIcE0mIPEHY2HCjSLilu4V6ejGIqUGlliZih232aU/PvH23rKBQiwReRNfWFU4axEOhDEtmhmk0xQoe7RkJFlUhkKX0fZhqG010k85OBHE90DdySbZ+jI8Ka7/7ghGivyNSV66xiu9QrLDhdqAJnDX3ge8GVp62TyV8q67HxOehLCHdvRsT85Lf9519sEwRPLRoY12DsU4mdsgEWJMxfCrH25B/2FIS7B+Ddl4w2vxGnQeC1FmV2ipWumbqQqsalyVoWCNDSwm9jsGOy7fSgxgagPXxLER7ujIuH7+IxJpei0+UiLXVNOmSRhdvluQI95LSIxXwwumseqKN5Hw8hgWJf8Wtyc28yivhU///kesApZoHFsskbJpoM7BYlllWnYgaraS01rVwzftsVZdjwHgUysokUyiwXl5s+RyL/q3jZw82BWQRgLxicCexDn98ZbNIO73Wm8yuOod+HhyUIpRdEu4UdVb/46EDTssHPFTUP+qU5Zcl/KdZ8jB6B7ZLatZu+zIAPhORCVlrWOVG01vE9r/QLwu0PGNcQku3xG5jHkyWY=

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
